// MOUSE CONFIG
#define MOUSEKEY_DELAY			100
#define MOUSEKEY_INTERVAL		50
#define	MOUSEKEY_MAX_SPEED		10
#define MOUSEKEY_TIME_TO_MAX		20
#define MOUSEKEY_WHEEL_MAX_SPEED   	8
#define MOUSEKEY_WHEEL_TIME_TO_MAX 	40

// AUTO SHIFT
#define AUTO_SHIFT_TIMEOUT 		200
#define NO_AUTO_SHIFT_ALPHA

// TAP DANCE
#define TAPPING_TERM 			125
